#Requirements file
- name: openshift-applier
  scm: git
  src: https://github.com/crossvale-inc/openshift-applier
  version: v2.0.9
- name: docker-importer
  scm: git
  src: https://github.com/crossvale-inc/docker-importer
  version: v0.2