#Requirements file
- name: openshift-applier
  scm: git
  src: https://github.com/crossvale-inc/openshift-applier
  version: v2.0.9
- name: skopeo-downloader
  scm: git
  src: https://github.com/crossvale-inc/skopeo-downloader
  version: v0.1